"""Init schema

Revision ID: a4ef29741ffc
Revises: 
Create Date: 2026-09-09 13:13:05.648806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4ef29741ffc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector',
    sa.Column('collector_id', sa.UUID(), nullable=False),
    sa.Column('preferred_language', sa.Enum('Hindi', 'Marathi', 'English', name='language_enum'), nullable=True),
    sa.Column('operating_district', sa.String(), nullable=True),
    sa.Column('operating_state', sa.String(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('total_transactions', sa.Integer(), nullable=True),
    sa.Column('total_earnings', sa.DECIMAL(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('phone_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('collector_id')
    )
    op.create_table('material',
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('CRT', 'LCD', 'PCB', 'Cable', 'Battery', 'Motor', 'Plastic', 'Mixed', name='material_category_enum'), nullable=True),
    sa.Column('sub_category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('approximate_weight', sa.DECIMAL(), nullable=True),
    sa.Column('condition', sa.Enum('Good', 'Damaged', 'Mixed', 'Unknown', name='condition_enum'), nullable=True),
    sa.Column('source_type', sa.Enum('Household', 'Commercial', 'Industrial', 'Unknown', name='source_type_enum'), nullable=True),
    sa.Column('estimated_value', sa.DECIMAL(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('material_id')
    )
    op.create_table('ml_sample',
    sa.Column('ml_sample_id', sa.UUID(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('material_category', sa.String(), nullable=True),
    sa.Column('material_sub_cat', sa.String(), nullable=True),
    sa.Column('weight_kg', sa.DECIMAL(), nullable=True),
    sa.Column('location_district', sa.String(), nullable=True),
    sa.Column('transaction_price', sa.DECIMAL(), nullable=True),
    sa.Column('label_source', sa.Enum('Human', 'Model', 'Crowdsourced', name='label_source_enum'), nullable=True),
    sa.Column('label_confidence', sa.DECIMAL(), nullable=True),
    sa.Column('split', sa.Enum('Train', 'Validation', 'Test', name='split_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('ml_sample_id')
    )
    op.create_table('recycler',
    sa.Column('recycler_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('facility_address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.DECIMAL(), nullable=True),
    sa.Column('longitude', sa.DECIMAL(), nullable=True),
    sa.Column('materials_accepted', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('auth_number', sa.String(), nullable=True),
    sa.Column('auth_status', sa.Enum('Active', 'Expired', 'Suspended', name='auth_status_enum'), nullable=True),
    sa.Column('auth_expiry_date', sa.Date(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('offered_rates', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('pickup_available', sa.Boolean(), nullable=True),
    sa.Column('service_radius_km', sa.Integer(), nullable=True),
    sa.Column('operating_hours', sa.String(), nullable=True),
    sa.Column('verified_by_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('recycler_id')
    )
    op.create_table('price',
    sa.Column('price_id', sa.UUID(), nullable=False),
    sa.Column('material_category', sa.String(), nullable=True),
    sa.Column('material_sub_cat', sa.String(), nullable=True),
    sa.Column('location_district', sa.String(), nullable=True),
    sa.Column('location_state', sa.String(), nullable=True),
    sa.Column('date_recorded', sa.Date(), nullable=True),
    sa.Column('buying_price', sa.DECIMAL(), nullable=True),
    sa.Column('selling_price', sa.DECIMAL(), nullable=True),
    sa.Column('unit', sa.Enum('kg', 'piece', 'lot', name='unit_enum'), nullable=True),
    sa.Column('recycler_id', sa.UUID(), nullable=True),
    sa.Column('market_price_low', sa.DECIMAL(), nullable=True),
    sa.Column('market_price_high', sa.DECIMAL(), nullable=True),
    sa.Column('source', sa.Enum('Platform', 'Manual', 'Scraped', name='source_enum'), nullable=True),
    sa.ForeignKeyConstraint(['recycler_id'], ['recycler.recycler_id'], ),
    sa.PrimaryKeyConstraint('price_id')
    )
    op.create_table('traceability',
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=True),
    sa.Column('photograph_paths', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('weight_at_collection', sa.DECIMAL(), nullable=True),
    sa.Column('weight_at_handover', sa.DECIMAL(), nullable=True),
    sa.Column('collection_gps', sa.String(), nullable=True),
    sa.Column('handover_gps', sa.String(), nullable=True),
    sa.Column('collection_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handover_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handover_ref_number', sa.String(), nullable=True),
    sa.Column('recycler_confirmation', sa.Boolean(), nullable=True),
    sa.Column('recycler_confirm_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qr_code_data', sa.String(), nullable=True),
    sa.Column('subsequent_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['material.material_id'], ),
    sa.PrimaryKeyConstraint('trace_id'),
    sa.UniqueConstraint('handover_ref_number')
    )
    op.create_table('transaction',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=True),
    sa.Column('collector_id', sa.UUID(), nullable=True),
    sa.Column('recycler_id', sa.UUID(), nullable=True),
    sa.Column('material_category', sa.String(), nullable=True),
    sa.Column('quantity_weight', sa.DECIMAL(), nullable=True),
    sa.Column('quoted_price', sa.DECIMAL(), nullable=True),
    sa.Column('final_price', sa.DECIMAL(), nullable=True),
    sa.Column('collection_location', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('handover_location', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('collection_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handover_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_method', sa.Enum('Cash', 'UPI', 'Bank', 'Pending', name='payment_method_enum'), nullable=True),
    sa.Column('payment_status', sa.Enum('Paid', 'Pending', 'Disputed', name='payment_status_enum'), nullable=True),
    sa.Column('transaction_status', sa.Enum('Created', 'Matched', 'Confirmed', 'Completed', 'Cancelled', name='transaction_status_enum'), nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['collector.collector_id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['material.material_id'], ),
    sa.ForeignKeyConstraint(['recycler_id'], ['recycler.recycler_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('traceability')
    op.drop_table('price')
    op.drop_table('recycler')
    op.drop_table('ml_sample')
    op.drop_table('material')
    op.drop_table('collector')
    # ### end Alembic commands ###
